#!/usr/bin/env bash
# Generated by setup_wsl.sh -- launches the Auto-MFA GUI against the conda
# env set up by that script. Safe to re-run setup_wsl.sh; it will
# regenerate this file identically.
#
# Properly *activate* the env (not just invoke its python by absolute
# path): MFA/Kaldi spawn their own command-line tools (fstcompile and
# friends, from openfst) by name via a PATH lookup, and some conda
# packages set other env vars via activation hooks. A bare absolute-path
# python invocation skips all of that, which is exactly what caused
# "Could not find 'fstcompile'" even though the file was right there in
# the env's bin/ folder.
source "/home/david/miniconda3/etc/profile.d/conda.sh"
conda activate "/home/david/miniconda3/envs/auto-mfa"
exec python "/mnt/c/Users/david/projects/Auto-MFA/app/main.py" "$@"
