#!/usr/bin/env bash
# Generated by setup_wsl.sh -- launches the Auto-MFA GUI against the conda
# env set up by that script. Safe to re-run setup_wsl.sh; it will
# regenerate this file identically.
exec "/home/david/miniconda3/envs/auto-mfa/bin/python" "/mnt/c/Users/david/projects/Auto-MFA/app/main.py" "$@"
