#!/usr/bin/env bash
# Set up Auto-MFA to run directly under WSL Ubuntu (or any Linux), instead of
# as a packaged Windows .exe.
#
# Why this exists: MFA wraps Kaldi, which spawns many short-lived
# subprocesses per alignment job. On native Windows that means paying
# CreateProcess overhead (no fork()) on every one of them, plus Windows
# Defender real-time-scanning freshly-extracted, unsigned binaries, plus a
# parallel (--num_jobs > 1) TextGrid export bug that has been observed
# silently dropping most of its own output on Windows. None of that applies
# running a normal conda-forge Linux build of MFA under WSL -- this is also
# MFA/Kaldi's actual primary, best-tested platform.
#
# Unlike build.ps1, this does NOT freeze the app into a standalone .exe or
# conda-pack/relocate the environment -- there's no need to, since we're not
# distributing this to someone else's machine. It just creates a normal
# conda env with MFA in it and runs the app straight from source against
# that env's python, the same way "Running from source (development)" in
# README.md already describes for a native Linux/Mac setup.
#
# Usage:
#   ./setup_wsl.sh
#   ./run.sh              # launches the GUI (this generates run.sh for you)
#
# Re-running this script is safe and fast -- it skips steps that are already
# done (existing Miniconda install, existing env).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONDA_DIR="${AUTO_MFA_CONDA_DIR:-$HOME/miniconda3}"
ENV_NAME="auto-mfa"
ENV_DIR="$CONDA_DIR/envs/$ENV_NAME"

step() { printf '\n=== %s\n' "$1"; }

if [ -n "${WSL_DISTRO_NAME:-}" ]; then
    case "$ROOT" in
        /mnt/c/*|/mnt/[a-z]/*)
            echo "NOTE: this project lives at $ROOT, on the Windows-side filesystem"
            echo "(under /mnt/...). That's fine for the small app source itself, but"
            echo "for real speed, point the GUI's 'Book folder' and output folder at"
            echo "paths INSIDE the Linux filesystem (e.g. ~/audiobooks), not /mnt/c/...:"
            echo "crossing that Windows<->Linux filesystem boundary for the audio"
            echo "files and MFA's own working files is slow and would eat into the"
            echo "exact overhead this script exists to avoid."
            ;;
    esac
fi

if [ ! -x "$CONDA_DIR/bin/conda" ]; then
    step "Downloading Miniconda into $CONDA_DIR (one-time)"
    installer="$(mktemp /tmp/miniconda-XXXXXX.sh)"
    curl -fsSL -o "$installer" \
        "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    bash "$installer" -b -p "$CONDA_DIR"
    rm -f "$installer"
fi

CONDA="$CONDA_DIR/bin/conda"

step "Configuring conda (conda-forge only)"
# Same reasoning as build.ps1: don't depend on Anaconda's commercial
# "defaults" channel (requires ToS acceptance). Every one of these is
# allowed to fail harmlessly (e.g. "defaults" already removed on a re-run).
"$CONDA" config --set auto_update_conda false || true
"$CONDA" config --remove channels defaults || true
"$CONDA" config --add channels conda-forge || true
"$CONDA" config --set channel_priority strict || true

if [ ! -x "$ENV_DIR/bin/python" ]; then
    step "Creating the MFA environment (conda-forge; downloads ~1-2 GB)"
    # `tk` is listed explicitly so tkinter is guaranteed to work -- don't
    # rely on it coming along for free with `python`, the same mistake that
    # caused the "no module named tkinter" issue on the Windows build.
    "$CONDA" create -p "$ENV_DIR" -y --override-channels -c conda-forge \
        "python=3.11" tk montreal-forced-aligner "kaldi=*=cpu*" ffmpeg
fi

step "Verifying tkinter and MFA both import cleanly"
"$ENV_DIR/bin/python" -c \
    "import tkinter, montreal_forced_aligner, kalpy; print('ok:', montreal_forced_aligner.__version__)"

launcher="$ROOT/run.sh"
cat > "$launcher" <<EOF
#!/usr/bin/env bash
# Generated by setup_wsl.sh -- launches the Auto-MFA GUI against the conda
# env set up by that script. Safe to re-run setup_wsl.sh; it will
# regenerate this file identically.
exec "$ENV_DIR/bin/python" "$ROOT/app/main.py" "\$@"
EOF
chmod +x "$launcher"

step "Done"
echo "Run the app with:"
echo "  $launcher"
