"""Generate the WSL/Linux shell script that runs an alignment job.

Kept separate from gui.py deliberately: everything here is pure string and
path manipulation with no Tk dependency, so it can be unit-tested on a
machine with no display (and no tkinter installed at all).
"""

import re
from pathlib import Path, PureWindowsPath

# Default location of the conda env created by setup_wsl.sh. Written into
# the generated script as an overridable shell variable rather than baked
# in, so a different install path only needs editing one line.
DEFAULT_CONDA_DIR = "$HOME/miniconda3"
DEFAULT_ENV_NAME = "auto-mfa"

# R2 (Cloudflare) storage the Govorim app serves audiobook audio from.
# The bucket name and S3 endpoint are not secrets -- the *keys* are, and
# they are deliberately never written into a generated script: it lives in
# a book folder next to files that get copied around, so the script reads
# credentials from an rclone remote configured once on the machine instead.
DEFAULT_R2_BUCKET = "govorim-audio"
DEFAULT_R2_ENDPOINT = (
    "https://34e5181838c8f719758264dbb7b02b46.r2.cloudflarestorage.com"
)
DEFAULT_R2_REMOTE = "r2"

_SLUG_STRIP_RE = re.compile(r"[^a-z0-9]+")


def to_wsl_path(path) -> str:
    """Translate a Windows path into the /mnt/<drive> path WSL sees.

    ``C:\\Users\\dave\\books`` -> ``/mnt/c/Users/dave/books``. Anything that
    isn't a drive-letter Windows path (already-POSIX input, a UNC share) is
    returned with separators normalized and otherwise left alone -- better
    to emit something the user can eyeball and fix than to mangle it.
    """
    raw = str(path)
    win = PureWindowsPath(raw)
    drive = win.drive  # e.g. "C:"
    if len(drive) == 2 and drive[1] == ":" and drive[0].isalpha():
        rest = raw[len(drive):].replace("\\", "/").lstrip("/")
        return f"/mnt/{drive[0].lower()}/{rest}"
    return raw.replace("\\", "/")


def slugify(name: str) -> str:
    """Best-effort ASCII slug for a book folder name.

    Cyrillic folder names slug to nothing useful, so an empty result falls
    back to a placeholder the user is expected to replace -- the slug ends
    up in every output filename, so it should be theirs, not a
    transliteration guess.
    """
    slug = _SLUG_STRIP_RE.sub("-", (name or "").lower()).strip("-")
    return slug or "book"


def shell_quote(value: str) -> str:
    """Single-quote a value for safe inclusion in the generated bash script."""
    return "'" + str(value).replace("'", "'\\''") + "'"


def run_command_for(script_wsl_path: str) -> str:
    """The exact command line to run a generated script.

    Always quoted: book folders routinely contain spaces ("marble head"),
    and an unquoted path silently becomes two arguments -- bash then
    reports "No such file or directory" for the fragment before the space,
    which is a confusing way to learn about a quoting bug.
    """
    return f"bash {shell_quote(script_wsl_path)}"


def build_script(slug: str, job_wsl_path: str, project_dir: str,
                 version: str = "") -> str:
    """The bash script that runs one alignment job under WSL/Linux."""
    script_name = f"align_{slug}.sh"
    job_dir = str(Path(job_wsl_path).parent)
    return f"""#!/usr/bin/env bash
# Auto-MFA alignment job for '{slug}'
# Generated by Auto-MFA{(' v' + version) if version else ''} -- safe to re-run, safe to edit.
#
# Run it from an Ubuntu (WSL) terminal:
#     {run_command_for(f"{job_dir}/{script_name}")}
#
# It aligns the audio to the FB2 text and writes Govorim-format JSONs
# ({slug}-ch01.json, ...) into the output folder set in the GUI.

set -euo pipefail

PROJECT={shell_quote(project_dir)}
JOB={shell_quote(job_wsl_path)}
CONDA_DIR="${{AUTO_MFA_CONDA_DIR:-{DEFAULT_CONDA_DIR}}}"
ENV_DIR="$CONDA_DIR/envs/{DEFAULT_ENV_NAME}"

if [ ! -x "$ENV_DIR/bin/python" ]; then
    echo "The Auto-MFA conda environment is missing at: $ENV_DIR" >&2
    echo "Create it first:  bash $PROJECT/setup_wsl.sh" >&2
    exit 1
fi

# Activate rather than calling the env's python by absolute path: MFA
# spawns openfst/kaldi command-line tools (fstcompile and friends) by name
# via a PATH lookup, so they have to actually be on PATH.
source "$CONDA_DIR/etc/profile.d/conda.sh"
conda activate "$ENV_DIR"

# Force UTF-8 regardless of the machine's locale: MFA writes Cyrillic
# corpus text through plain open() calls with no explicit encoding.
export PYTHONUTF8=1
export PYTHONIOENCODING=utf-8

cd "$PROJECT"
exec python "$PROJECT/app/main.py" --worker align "$JOB"
"""


def build_install_script(slug: str, repo_dir_wsl: str, fb2_src_wsl: str,
                         json_src_dir_wsl: str, title: str = "",
                         author: str = "", category: str = "Works",
                         narrator: str = "audiobook",
                         source_note: str = "owned recording",
                         r2_folder: str = "",
                         r2_base: str = "",
                         version: str = "") -> str:
    """Script that installs a finished book into the Govorim app.

    Three things have to line up for a book to actually work in the app,
    and doing any one of them by hand is how books end up half-registered:

    1. the FB2 in ``public/books/novel/`` -- this is what the catalogue
       keys off, and what the reader displays;
    2. the chapter JSONs in ``public/books/audio/<slug>/NNN.json`` --
       renamed from this tool's ``<slug>-chNNN.json`` to the app's own
       convention;
    3. an ``index.json`` entry whose ``audiobook.chapters`` lists those
       files **in order**. The catalogue does not glob the audio folder;
       an unlisted chapter simply doesn't exist as far as the app is
       concerned.

    The heavy lifting is Python inside the script rather than shell, so
    the JSON edit is a real parse-modify-write (preserving every other
    entry and any hand-set fields) instead of fragile text munging, and
    so chapter ordering comes from numeric sorting rather than shell glob
    collation.
    """
    return f"""#!/usr/bin/env bash
# Auto-MFA -- install '{slug}' into the Govorim app
# Generated by Auto-MFA{(' v' + version) if version else ''} -- safe to re-run.
#
# Copies the FB2 and the aligned chapter JSONs into the repo, then adds or
# updates this book's entry in public/books/index.json so the app can see
# it. Re-running overwrites this book's files and entry, and leaves every
# other book alone.

set -euo pipefail

REPO={shell_quote(repo_dir_wsl)}
FB2={shell_quote(fb2_src_wsl)}
JSON_SRC={shell_quote(json_src_dir_wsl)}
SLUG={shell_quote(slug)}
TITLE={shell_quote(title)}
AUTHOR={shell_quote(author)}
CATEGORY={shell_quote(category)}
NARRATOR={shell_quote(narrator)}
SOURCE_NOTE={shell_quote(source_note)}
R2_FOLDER={shell_quote(r2_folder)}
R2_BASE={shell_quote(r2_base)}
export REPO FB2 JSON_SRC SLUG TITLE AUTHOR CATEGORY NARRATOR SOURCE_NOTE
export R2_FOLDER R2_BASE

if [ ! -d "$REPO/public/books" ]; then
    echo "Not a Govorim checkout: $REPO" >&2
    echo "(expected to find public/books/ inside it)" >&2
    exit 1
fi
if [ ! -f "$FB2" ]; then
    echo "FB2 not found: $FB2" >&2
    exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
    echo "python3 is required." >&2
    exit 1
fi

python3 - <<'PY'
import json
import os
import re
import shutil
from pathlib import Path
from urllib.parse import quote

repo = Path(os.environ["REPO"])
slug = os.environ["SLUG"]
books = repo / "public" / "books"
novel_dir = books / "novel"
audio_dir = books / "audio" / slug
index_path = books / "index.json"

fb2_src = Path(os.environ["FB2"])
json_src = Path(os.environ["JSON_SRC"])

novel_dir.mkdir(parents=True, exist_ok=True)
audio_dir.mkdir(parents=True, exist_ok=True)

# 1. The FB2. Named after the slug so the catalogue key is predictable
# and two books can't collide on a source filename.
fb2_dest = novel_dir / f"{{slug}}.fb2"
shutil.copyfile(fb2_src, fb2_dest)
print(f"FB2      -> public/books/novel/{{fb2_dest.name}}")

# 2. The chapter JSONs, renamed to the app's NNN.json convention.
# Sorted numerically on the trailing chapter number, NOT lexicographically:
# ch100 collates before ch99 as text, which would silently reorder a book.
def chapter_number(path):
    m = re.search(r"-ch(\\d+)\\.json$", path.name)
    return int(m.group(1)) if m else 0

found = sorted((p for p in json_src.glob(f"{{slug}}-ch*.json")),
               key=chapter_number)
if not found:
    raise SystemExit(f"No {{slug}}-ch*.json files in {{json_src}} -- "
                     f"run the alignment script first.")

# Clear out a previous install of THIS book so a re-run after a shorter
# re-alignment can't leave orphan chapters behind that index.json no
# longer references but the folder still contains.
for stale in audio_dir.glob("*.json"):
    stale.unlink()

# audio_url is written when the chapter JSON is generated, from the R2
# folder set in the GUI. If that was left blank the URL is a bare
# filename, which 404s in the app -- so repair it here rather than making
# anyone re-run a multi-minute alignment just to change a string.
r2_folder = os.environ.get("R2_FOLDER", "").strip().strip("/")
r2_base = os.environ.get("R2_BASE", "").rstrip("/")

chapters = []
fixed_urls = 0
for i, src in enumerate(found, start=1):
    dest = audio_dir / f"{{i:03d}}.json"
    doc = json.loads(src.read_text(encoding="utf-8"))
    url = str(doc.get("audio_url", ""))
    if r2_folder and r2_base and not url.startswith(("http://", "https://")):
        # Percent-encode: these filenames are routinely Cyrillic with
        # spaces, which is not valid in a URL as-is.
        name = quote(url.rsplit("/", 1)[-1])
        doc["audio_url"] = f"{{r2_base}}/{{quote(r2_folder)}}/{{name}}"
        fixed_urls += 1
    dest.write_text(json.dumps(doc, ensure_ascii=False, indent=2),
                    encoding="utf-8")
    chapters.append(f"audio/{{slug}}/{{dest.name}}")
print(f"chapters -> public/books/audio/{{slug}}/  ({{len(chapters)}} file(s))")
if fixed_urls:
    print(f"audio_url -> pointed {{fixed_urls}} chapter(s) at {{r2_folder}}/")
elif not str(json.loads(found[0].read_text(encoding='utf-8'))
             .get("audio_url", "")).startswith(("http://", "https://")):
    print("WARNING: audio_url is a bare filename and no R2 folder was set -- "
          "the audio will not load until those URLs are fixed.")

# 3. The catalogue entry. index.json is a list; the manifest generator
# preserves hand-set fields on existing entries, so anything set here (or
# edited later by hand) survives the next build.
entries = []
if index_path.exists():
    backup = index_path.with_suffix(".json.bak")
    if not backup.exists():
        shutil.copyfile(index_path, backup)
        print(f"backed up index.json -> {{backup.name}}")
    entries = json.loads(index_path.read_text(encoding="utf-8"))

filename = f"novel/{{fb2_dest.name}}"
entry = next((e for e in entries if e.get("filename") == filename), None)
created = entry is None
if entry is None:
    entry = {{"filename": filename}}
    entries.append(entry)

# Don't clobber a title/author already curated in the repo.
if os.environ.get("TITLE") and not entry.get("title"):
    entry["title"] = os.environ["TITLE"]
entry.setdefault("title", slug.replace("-", " ").title())
if os.environ.get("AUTHOR") and not entry.get("author"):
    entry["author"] = os.environ["AUTHOR"]
entry.setdefault("category", os.environ.get("CATEGORY") or "Works")

# The chapter list IS regenerated every run -- it must match what was
# just copied in, or the app asks for files that aren't there.
entry["audiobook"] = {{
    "narrator": os.environ.get("NARRATOR") or "audiobook",
    "source": os.environ.get("SOURCE_NOTE") or "owned recording",
    "chapters": chapters,
}}

index_path.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\\n",
                      encoding="utf-8")
print(f"index.json -> {{'added' if created else 'updated'}} '{{entry['title']}}' "
      f"({{len(entries)}} book(s) in the catalogue)")
PY

echo
echo "Done. Check it renders, then commit:"
echo "    cd \\"$REPO\\""
echo "    git add public/books"
echo "    git commit -m \\"Add $SLUG audiobook alignment\\""
echo "    git push"
echo
echo "Vercel redeploys on push (1-2 min). Hard-refresh the site afterwards"
echo "(Ctrl+Shift+R) -- the old chapter JSONs sit in the browser cache."
"""


def build_upload_script(r2_folder: str, source_dir_wsl: str,
                        list_path_wsl: str, bucket: str = DEFAULT_R2_BUCKET,
                        endpoint: str = DEFAULT_R2_ENDPOINT,
                        remote: str = DEFAULT_R2_REMOTE,
                        version: str = "") -> str:
    """Script that uploads this book's audio files to R2.

    Deliberately uploads only the files listed in *list_path_wsl* (the
    paired audio, written alongside this script) rather than syncing the
    whole folder -- a book folder also holds the FB2, the generated
    scripts, and the output JSONs, none of which belong in the audio
    bucket.

    No credentials are embedded. The script requires an rclone remote
    configured once on the machine, and prints the exact command to create
    one if it is missing.
    """
    return f"""#!/usr/bin/env bash
# Auto-MFA R2 upload for '{r2_folder}'
# Generated by Auto-MFA{(' v' + version) if version else ''} -- safe to re-run.
#
# Uploads this book's audio files to:
#     {bucket}/{r2_folder}/
# which is what the generated JSONs' audio_url fields point at.
#
# Re-running is safe: rclone copy skips files already present with the
# same size and modification time.

set -euo pipefail

REMOTE="${{AUTO_MFA_R2_REMOTE:-{remote}}}"
BUCKET={shell_quote(bucket)}
FOLDER={shell_quote(r2_folder)}
SRC={shell_quote(source_dir_wsl)}
LIST={shell_quote(list_path_wsl)}

if ! command -v rclone >/dev/null 2>&1; then
    echo "rclone is not installed. Install it with:" >&2
    echo "    sudo apt-get install -y rclone" >&2
    exit 1
fi

if ! rclone listremotes | grep -qx "$REMOTE:"; then
    echo "No rclone remote named '$REMOTE' is configured." >&2
    echo >&2
    echo "Create it once (paste your R2 access key and secret):" >&2
    echo "    rclone config create $REMOTE s3 provider=Cloudflare \\\\" >&2
    echo "        access_key_id=YOUR_ACCESS_KEY_ID \\\\" >&2
    echo "        secret_access_key=YOUR_SECRET_ACCESS_KEY \\\\" >&2
    echo "        endpoint={endpoint} \\\\" >&2
    echo "        region=auto" >&2
    echo >&2
    echo "Keys come from the Cloudflare dashboard: R2 > Manage API tokens." >&2
    exit 1
fi

if [ ! -f "$LIST" ]; then
    echo "Missing file list: $LIST" >&2
    echo "Re-generate the upload script from the Auto-MFA GUI." >&2
    exit 1
fi

echo "Uploading $(wc -l < "$LIST") file(s) to $REMOTE:$BUCKET/$FOLDER/ ..."
rclone copy "$SRC" "$REMOTE:$BUCKET/$FOLDER/" \\
    --files-from "$LIST" \\
    --progress \\
    --transfers 8

echo
echo "Done. Now in $BUCKET/$FOLDER/:"
rclone lsf "$REMOTE:$BUCKET/$FOLDER/"
"""

