"""Generate the WSL/Linux shell script that runs an alignment job.

Kept separate from gui.py deliberately: everything here is pure string and
path manipulation with no Tk dependency, so it can be unit-tested on a
machine with no display (and no tkinter installed at all).
"""

import re
from pathlib import Path, PureWindowsPath

# Default location of the conda env created by setup_wsl.sh. Written into
# the generated script as an overridable shell variable rather than baked
# in, so a different install path only needs editing one line.
DEFAULT_CONDA_DIR = "$HOME/miniconda3"
DEFAULT_ENV_NAME = "auto-mfa"

# R2 (Cloudflare) storage the Govorim app serves audiobook audio from.
# The bucket name and S3 endpoint are not secrets -- the *keys* are, and
# they are deliberately never written into a generated script: it lives in
# a book folder next to files that get copied around, so the script reads
# credentials from an rclone remote configured once on the machine instead.
DEFAULT_R2_BUCKET = "govorim-audio"
DEFAULT_R2_ENDPOINT = (
    "https://34e5181838c8f719758264dbb7b02b46.r2.cloudflarestorage.com"
)
DEFAULT_R2_REMOTE = "r2"

_SLUG_STRIP_RE = re.compile(r"[^a-z0-9]+")


def to_wsl_path(path) -> str:
    """Translate a Windows path into the /mnt/<drive> path WSL sees.

    ``C:\\Users\\dave\\books`` -> ``/mnt/c/Users/dave/books``. Anything that
    isn't a drive-letter Windows path (already-POSIX input, a UNC share) is
    returned with separators normalized and otherwise left alone -- better
    to emit something the user can eyeball and fix than to mangle it.
    """
    raw = str(path)
    win = PureWindowsPath(raw)
    drive = win.drive  # e.g. "C:"
    if len(drive) == 2 and drive[1] == ":" and drive[0].isalpha():
        rest = raw[len(drive):].replace("\\", "/").lstrip("/")
        return f"/mnt/{drive[0].lower()}/{rest}"
    return raw.replace("\\", "/")


def slugify(name: str) -> str:
    """Best-effort ASCII slug for a book folder name.

    Cyrillic folder names slug to nothing useful, so an empty result falls
    back to a placeholder the user is expected to replace -- the slug ends
    up in every output filename, so it should be theirs, not a
    transliteration guess.
    """
    slug = _SLUG_STRIP_RE.sub("-", (name or "").lower()).strip("-")
    return slug or "book"


def shell_quote(value: str) -> str:
    """Single-quote a value for safe inclusion in the generated bash script."""
    return "'" + str(value).replace("'", "'\\''") + "'"


def run_command_for(script_wsl_path: str) -> str:
    """The exact command line to run a generated script.

    Always quoted: book folders routinely contain spaces ("marble head"),
    and an unquoted path silently becomes two arguments -- bash then
    reports "No such file or directory" for the fragment before the space,
    which is a confusing way to learn about a quoting bug.
    """
    return f"bash {shell_quote(script_wsl_path)}"


def build_script(slug: str, job_wsl_path: str, project_dir: str,
                 version: str = "") -> str:
    """The bash script that runs one alignment job under WSL/Linux."""
    script_name = f"align_{slug}.sh"
    job_dir = str(Path(job_wsl_path).parent)
    return f"""#!/usr/bin/env bash
# Auto-MFA alignment job for '{slug}'
# Generated by Auto-MFA{(' v' + version) if version else ''} -- safe to re-run, safe to edit.
#
# Run it from an Ubuntu (WSL) terminal:
#     {run_command_for(f"{job_dir}/{script_name}")}
#
# It aligns the audio to the FB2 text and writes Govorim-format JSONs
# ({slug}-ch01.json, ...) into the output folder set in the GUI.

set -euo pipefail

PROJECT={shell_quote(project_dir)}
JOB={shell_quote(job_wsl_path)}
CONDA_DIR="${{AUTO_MFA_CONDA_DIR:-{DEFAULT_CONDA_DIR}}}"
ENV_DIR="$CONDA_DIR/envs/{DEFAULT_ENV_NAME}"

if [ ! -x "$ENV_DIR/bin/python" ]; then
    echo "The Auto-MFA conda environment is missing at: $ENV_DIR" >&2
    echo "Create it first:  bash $PROJECT/setup_wsl.sh" >&2
    exit 1
fi

# Activate rather than calling the env's python by absolute path: MFA
# spawns openfst/kaldi command-line tools (fstcompile and friends) by name
# via a PATH lookup, so they have to actually be on PATH.
source "$CONDA_DIR/etc/profile.d/conda.sh"
conda activate "$ENV_DIR"

# Force UTF-8 regardless of the machine's locale: MFA writes Cyrillic
# corpus text through plain open() calls with no explicit encoding.
export PYTHONUTF8=1
export PYTHONIOENCODING=utf-8

cd "$PROJECT"
exec python "$PROJECT/app/main.py" --worker align "$JOB"
"""


def build_upload_script(r2_folder: str, source_dir_wsl: str,
                        list_path_wsl: str, bucket: str = DEFAULT_R2_BUCKET,
                        endpoint: str = DEFAULT_R2_ENDPOINT,
                        remote: str = DEFAULT_R2_REMOTE,
                        version: str = "") -> str:
    """Script that uploads this book's audio files to R2.

    Deliberately uploads only the files listed in *list_path_wsl* (the
    paired audio, written alongside this script) rather than syncing the
    whole folder -- a book folder also holds the FB2, the generated
    scripts, and the output JSONs, none of which belong in the audio
    bucket.

    No credentials are embedded. The script requires an rclone remote
    configured once on the machine, and prints the exact command to create
    one if it is missing.
    """
    return f"""#!/usr/bin/env bash
# Auto-MFA R2 upload for '{r2_folder}'
# Generated by Auto-MFA{(' v' + version) if version else ''} -- safe to re-run.
#
# Uploads this book's audio files to:
#     {bucket}/{r2_folder}/
# which is what the generated JSONs' audio_url fields point at.
#
# Re-running is safe: rclone copy skips files already present with the
# same size and modification time.

set -euo pipefail

REMOTE="${{AUTO_MFA_R2_REMOTE:-{remote}}}"
BUCKET={shell_quote(bucket)}
FOLDER={shell_quote(r2_folder)}
SRC={shell_quote(source_dir_wsl)}
LIST={shell_quote(list_path_wsl)}

if ! command -v rclone >/dev/null 2>&1; then
    echo "rclone is not installed. Install it with:" >&2
    echo "    sudo apt-get install -y rclone" >&2
    exit 1
fi

if ! rclone listremotes | grep -qx "$REMOTE:"; then
    echo "No rclone remote named '$REMOTE' is configured." >&2
    echo >&2
    echo "Create it once (paste your R2 access key and secret):" >&2
    echo "    rclone config create $REMOTE s3 provider=Cloudflare \\\\" >&2
    echo "        access_key_id=YOUR_ACCESS_KEY_ID \\\\" >&2
    echo "        secret_access_key=YOUR_SECRET_ACCESS_KEY \\\\" >&2
    echo "        endpoint={endpoint} \\\\" >&2
    echo "        region=auto" >&2
    echo >&2
    echo "Keys come from the Cloudflare dashboard: R2 > Manage API tokens." >&2
    exit 1
fi

if [ ! -f "$LIST" ]; then
    echo "Missing file list: $LIST" >&2
    echo "Re-generate the upload script from the Auto-MFA GUI." >&2
    exit 1
fi

echo "Uploading $(wc -l < "$LIST") file(s) to $REMOTE:$BUCKET/$FOLDER/ ..."
rclone copy "$SRC" "$REMOTE:$BUCKET/$FOLDER/" \\
    --files-from "$LIST" \\
    --progress \\
    --transfers 8

echo
echo "Done. Now in $BUCKET/$FOLDER/:"
rclone lsf "$REMOTE:$BUCKET/$FOLDER/"
"""

