"""Generate the WSL/Linux shell script that runs an alignment job.

Kept separate from gui.py deliberately: everything here is pure string and
path manipulation with no Tk dependency, so it can be unit-tested on a
machine with no display (and no tkinter installed at all).
"""

import re
from pathlib import Path, PureWindowsPath

# Default location of the conda env created by setup_wsl.sh. Written into
# the generated script as an overridable shell variable rather than baked
# in, so a different install path only needs editing one line.
DEFAULT_CONDA_DIR = "$HOME/miniconda3"
DEFAULT_ENV_NAME = "auto-mfa"

_SLUG_STRIP_RE = re.compile(r"[^a-z0-9]+")


def to_wsl_path(path) -> str:
    """Translate a Windows path into the /mnt/<drive> path WSL sees.

    ``C:\\Users\\dave\\books`` -> ``/mnt/c/Users/dave/books``. Anything that
    isn't a drive-letter Windows path (already-POSIX input, a UNC share) is
    returned with separators normalized and otherwise left alone -- better
    to emit something the user can eyeball and fix than to mangle it.
    """
    raw = str(path)
    win = PureWindowsPath(raw)
    drive = win.drive  # e.g. "C:"
    if len(drive) == 2 and drive[1] == ":" and drive[0].isalpha():
        rest = raw[len(drive):].replace("\\", "/").lstrip("/")
        return f"/mnt/{drive[0].lower()}/{rest}"
    return raw.replace("\\", "/")


def slugify(name: str) -> str:
    """Best-effort ASCII slug for a book folder name.

    Cyrillic folder names slug to nothing useful, so an empty result falls
    back to a placeholder the user is expected to replace -- the slug ends
    up in every output filename, so it should be theirs, not a
    transliteration guess.
    """
    slug = _SLUG_STRIP_RE.sub("-", (name or "").lower()).strip("-")
    return slug or "book"


def shell_quote(value: str) -> str:
    """Single-quote a value for safe inclusion in the generated bash script."""
    return "'" + str(value).replace("'", "'\\''") + "'"


def run_command_for(script_wsl_path: str) -> str:
    """The exact command line to run a generated script.

    Always quoted: book folders routinely contain spaces ("marble head"),
    and an unquoted path silently becomes two arguments -- bash then
    reports "No such file or directory" for the fragment before the space,
    which is a confusing way to learn about a quoting bug.
    """
    return f"bash {shell_quote(script_wsl_path)}"


def build_script(slug: str, job_wsl_path: str, project_dir: str,
                 version: str = "") -> str:
    """The bash script that runs one alignment job under WSL/Linux."""
    script_name = f"align_{slug}.sh"
    job_dir = str(Path(job_wsl_path).parent)
    return f"""#!/usr/bin/env bash
# Auto-MFA alignment job for '{slug}'
# Generated by Auto-MFA{(' v' + version) if version else ''} -- safe to re-run, safe to edit.
#
# Run it from an Ubuntu (WSL) terminal:
#     {run_command_for(f"{job_dir}/{script_name}")}
#
# It aligns the audio to the FB2 text and writes Govorim-format JSONs
# ({slug}-ch01.json, ...) into the output folder set in the GUI.

set -euo pipefail

PROJECT={shell_quote(project_dir)}
JOB={shell_quote(job_wsl_path)}
CONDA_DIR="${{AUTO_MFA_CONDA_DIR:-{DEFAULT_CONDA_DIR}}}"
ENV_DIR="$CONDA_DIR/envs/{DEFAULT_ENV_NAME}"

if [ ! -x "$ENV_DIR/bin/python" ]; then
    echo "The Auto-MFA conda environment is missing at: $ENV_DIR" >&2
    echo "Create it first:  bash $PROJECT/setup_wsl.sh" >&2
    exit 1
fi

# Activate rather than calling the env's python by absolute path: MFA
# spawns openfst/kaldi command-line tools (fstcompile and friends) by name
# via a PATH lookup, so they have to actually be on PATH.
source "$CONDA_DIR/etc/profile.d/conda.sh"
conda activate "$ENV_DIR"

# Force UTF-8 regardless of the machine's locale: MFA writes Cyrillic
# corpus text through plain open() calls with no explicit encoding.
export PYTHONUTF8=1
export PYTHONIOENCODING=utf-8

cd "$PROJECT"
exec python "$PROJECT/app/main.py" --worker align "$JOB"
"""
