"""Generate everything needed to align, upload and install ONE book.

The GUI does this interactively, a book at a time, with the pairing done by
hand. This does the same for a book whose pairing needs no judgement --
where the audio files and the FB2's chapters correspond one to one, in
order -- and chains the three generated scripts into a single command, so a
book can be run start to finish without sitting in front of it.

    python3 tools/make_book_run.py \\
        --folder "/mnt/c/Users/david/Downloads/audiobooks/<book>" \\
        --slug moya-strana --r2-folder moya-strana \\
        --repo /mnt/c/Users/david/projects/govorim-app \\
        --work /mnt/c/Users/david/Downloads/audiobooks/_runs

Writes into <work>/<slug>/ and prints the one command to run.

Audio is staged into <work>/<slug>/audio as 01.mp3, 02.mp3, ... rather than
being read from the book folder directly. The staged name is what ends up
in every chapter's audio_url and therefore in the R2 bucket, and the
originals are routinely named things like "chapter 01 Moya lyubimaya
strana.mp3" -- legal, but it turns every URL into a percent-encoded mouthful
and makes the bucket hard to read. Staging copies rather than renames: the
originals are the only copy of the recording and this tool does not touch
them.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import fb2, scriptgen  # noqa: E402
from app.govorim import DEFAULT_R2_BASE  # noqa: E402
from app import __version__  # noqa: E402


def build(folder: Path, slug: str, r2_folder: str, repo: str, work: Path,
          title: str = "", author: str = "", narrator: str = "audiobook",
          num_jobs: int = 2) -> Path:
    fb2_path = fb2.find_fb2(folder)
    chapters = fb2.extract_chapters(fb2_path)
    audio = fb2.find_audio_files(folder)

    if len(audio) != len(chapters):
        raise SystemExit(
            f"{folder.name}: {len(audio)} audio file(s) but {len(chapters)} "
            f"chapter(s).\n"
            f"This tool only handles the one-file-per-chapter case, where the "
            f"pairing needs no judgement. Pair this one in the GUI instead, "
            f"or split/join the audio first."
        )

    meta = fb2.extract_metadata(fb2_path)
    title = title or meta.get("title") or slug
    author = author or meta.get("author") or ""

    out = Path(work) / slug
    staged_dir = out / "audio"
    json_dir = out / "json"
    out.mkdir(parents=True, exist_ok=True)

    # Staged names, in pairing order. Width follows the count so 100 sorts
    # after 99 in the bucket listing as well as in the pairing.
    width = max(2, len(str(len(audio))))
    staged = [f"{i:0{width}d}{src.suffix.lower()}"
              for i, src in enumerate(audio, start=1)]

    job = {
        "pairs": [
            {"audio": str(staged_dir / name), "title": ch["title"],
             "text": ch["text"]}
            for name, ch in zip(staged, chapters)
        ],
        "output_dir": str(json_dir),
        "govorim_slug": slug,
        "r2_folder": r2_folder,
        "num_jobs": num_jobs,
        "acoustic_model": "russian_mfa",
        "dictionary": "russian_mfa",
    }
    job_path = out / f"{slug}.job.json"
    job_path.write_text(json.dumps(job, ensure_ascii=False, indent=2),
                        encoding="utf-8")

    # The upload script uploads exactly what's listed here, so the bucket
    # never picks up the FB2, the scripts or the JSONs sitting nearby.
    list_path = out / "upload_list.txt"
    list_path.write_text("\n".join(staged) + "\n", encoding="utf-8")

    project = str(Path(__file__).resolve().parent.parent)
    (out / f"align_{slug}.sh").write_text(
        scriptgen.build_script(slug, str(job_path), project, __version__),
        encoding="utf-8")
    (out / f"upload_{slug}.sh").write_text(
        scriptgen.build_upload_script(r2_folder, str(staged_dir),
                                      str(list_path), version=__version__),
        encoding="utf-8")
    (out / f"install_{slug}.sh").write_text(
        scriptgen.build_install_script(
            slug, repo, str(fb2_path), str(json_dir), title=title,
            author=author, narrator=narrator, r2_folder=r2_folder,
            r2_base=DEFAULT_R2_BASE, version=__version__),
        encoding="utf-8")

    # Staging is a script step rather than something done here: it copies
    # gigabytes, and it belongs in the same log as everything else.
    copies = "\n".join(
        f"cp -n {scriptgen.shell_quote(str(src))} \"$STAGE\"/{name}"
        for src, name in zip(audio, staged))

    run_path = out / f"run_{slug}.sh"
    run_path.write_text(f"""#!/usr/bin/env bash
# Auto-MFA -- run '{slug}' end to end
# Generated by Auto-MFA v{__version__}.
#
#   {scriptgen.run_command_for(str(run_path))}
#
# Four steps, in order: stage the audio under short names, align it against
# the FB2, upload the audio to R2, install the result into the Govorim app.
# Every step is safe to re-run; staging and uploading skip what's already
# there, and aligning simply overwrites its own output.
#
# Progress goes to the terminal AND to {out.name}/run.log, so a run left
# overnight can be read back in the morning.

set -euo pipefail
cd "$(dirname "$0")"
exec > >(tee -a run.log) 2>&1

echo "=================================================================="
echo "{title}"
echo "{len(audio)} audio file(s) -> {len(chapters)} chapter(s)   slug={slug}"
echo "started $(date '+%Y-%m-%d %H:%M:%S')"
echo "=================================================================="

STAGE={scriptgen.shell_quote(str(staged_dir))}
mkdir -p "$STAGE"

echo
echo "--- 1/4  staging audio ------------------------------------------"
{copies}
echo "staged $(ls -1 "$STAGE" | wc -l) file(s) in $STAGE"

echo
echo "--- 2/4  aligning (this is the long one) ------------------------"
bash {scriptgen.shell_quote(str(out / f'align_{slug}.sh'))}

echo
echo "--- 3/4  uploading audio to R2 ----------------------------------"
bash {scriptgen.shell_quote(str(out / f'upload_{slug}.sh'))}

echo
echo "--- 4/4  installing into Govorim --------------------------------"
bash {scriptgen.shell_quote(str(out / f'install_{slug}.sh'))}

echo
echo "=================================================================="
echo "'{slug}' done at $(date '+%Y-%m-%d %H:%M:%S')"
echo
echo "Then, to publish:"
echo "    cd {repo}"
echo "    git add public/books && git commit -m 'Re-align {slug}' && git push"
echo "=================================================================="
""", encoding="utf-8")

    print(f"Book:     {title}" + (f" -- {author}" if author else ""))
    print(f"FB2:      {fb2_path.name}")
    print(f"Chapters: {len(chapters)}   Audio: {len(audio)}   (paired in order)")
    print(f"Written:  {out}")
    print()
    print("Run it with:")
    print(f"    {scriptgen.run_command_for(str(run_path))}")
    return run_path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--folder", required=True)
    ap.add_argument("--slug", required=True)
    ap.add_argument("--r2-folder", required=True)
    ap.add_argument("--repo", required=True)
    ap.add_argument("--work", required=True)
    ap.add_argument("--title", default="")
    ap.add_argument("--author", default="")
    ap.add_argument("--narrator", default="audiobook")
    ap.add_argument("--num-jobs", type=int, default=2)
    a = ap.parse_args()
    build(Path(a.folder), a.slug, a.r2_folder, a.repo, Path(a.work),
          title=a.title, author=a.author, narrator=a.narrator,
          num_jobs=a.num_jobs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
